### ISSUE TITLE
Needs new maintainer or maintainers

### ISSUE THREAD

**Issue by terceiro** [terceiro/awesome-freedesktop#30]
Hello everyone. Unfortunately I do not use awesome anymore for some time already, and therefore I am not maintaining this codebase.

I urge all the people who have forked and that have sent pull requests to come together and maintain a single codebase that everyone can benefit from. Maybe create an organization and have a central repository there, or maybe something else. I am open to moving this repository to that organization If you think that's useful (I assume github will redirect people coming here to that new location)

**Comment by copycat-killer** [comment]
@terceiro Hi Antonio, since the introduction of menubar as awesome core library, which is based and carries on your work, it was easy enough for me to adapt the code to latest Lua and awesome API:

https://github.com/copycat-killer/awesome-freedesktop

The menu is pretty much complete, while the desktop icons are rather simple, and that's where my future work will go. I am able to maintain the code by myself, but of course I'd be happy to share it within a GitHub organization, if other people is willing to help. There's already a TODO list for stuff I'd like to implement.

Meanwhile, the repository linked above is a functional Awesome 3.5+ port.

**Comment by terceiro** [comment]
hello @copycat-killer thanks for working on this, I'm happy it's been useful. I am inclined to delete everything in this repository and point to yours. Are you OK with that?

**Comment by copycat-killer** [comment]
Yeah, no problem.

**Comment by terceiro** [comment]
cool, great.
